---
- name: add nginx repo
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo
- name: install nginx
  action: yum name=nginx state=present
- name: add nginx user
  user: name=nginx group=nginx createhome=no
- name: nginx user join vagrant group
  user: name=nginx state=present groups={{ user_name }}
- name: config nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx
