---
- name: install php-fpm
  action: yum name=php-fpm state=present enablerepo=remi-php55
- name: config php-fpm
  copy: src=php-fpm.conf dest=/etc/php-fpm.conf
  notify:
    - restart php-fpm
- name: config php-fpm pool
  copy: src=www.conf dest=/etc/php-fpm.d/www.conf
  notify:
    - restart php-fpm
- name: change group session directory
  command: chown root:nginx /var/lib/php/{{ item }}
  with_items:
    - session
    - wsdlcache
  notify:
    - restart php-fpm
