---
- name: install newrelic php agent
  action: yum name=newrelic-php5 state=present
  notify:
    - restart php-fpm
    - restart nginx
    - restart newrelic-sysmond
- name: check newrelic-install executed
  command: ls /usr/lib64/php/modules/newrelic.so
  register: result
  ignore_errors: True
- name: exec newrelic-install
  shell: NR_INSTALL_SILENT=true newrelic-install install
  notify:
    - restart php-fpm
    - restart nginx
- name: configure newrelic php agent
  template:
    src: newrelic.ini.j2
    dest: /etc/php.d/newrelic.ini
    group: root
    owner: root
    mode: 0640
  notify:
    - restart php-fpm
    - restart nginx
