---
- name: add mariadb repo
  copy: src=mariadb.repo dest=/etc/yum.repos.d/mariadb.repo
- name: install mariadb
  action: yum name={{ item }} state=present
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MariaDB-devel
    - MariaDB-compat
    - MySQL-python
- name: config mariadb
  copy: src=server.cnf dest=/etc/my.cnf.d/server.cnf
  notify:
    - restart mariadb
- name: start database service
  action: service name=mysql state=running
