---
- name: install php
  action: yum name={{ item }} state=present enablerepo=remi-php56
  with_items:
    - php
    - php-cli
    - php-common
    - php-devel
- name: install php modules
  action: yum name={{ item }} state=present enablerepo=remi,remi-php56
  with_items:
    - php-mbstring
    - php-mcrypt
    - php-mysql
    - php-pdo
    - php-xml
    - php-opcache
    - php-pecl-memcached
- name: install composer
  shell:
    curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f /home/vagrant/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer
