---
- name: install php
  action: yum name={{ item }} state=present enablerepo=remi-php55
  with_items:
    - php
    - php-cli
    - php-common
    - php-devel
    - php-fpm
- name: install php modules
  action: yum name={{ item }} state=present enablerepo=remi,remi-php55
  with_items:
    - php-mbstring
    - php-mcrypt
    - php-mysql
    - php-pdo
    - php-xml
    - php-opcache
    - php-pecl-memcached
- name: config php-fpm
  copy: src=php-fpm.conf dest=/etc/php-fpm.conf
  notify:
    - restart php-fpm
- name: config php-fpm pool
  copy: src=www.conf dest=/etc/php-fpm.d/www.conf
  notify:
    - restart php-fpm
- name: change group session directory
  command: chown root:nginx /var/lib/php/{{ item }}
  with_items:
    - session
    - wsdlcache
  notify:
    - restart php-fpm
- name: install composer
  shell:
    curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f /home/vagrant/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer
- name: install newrelic php agent
  action: yum name=newrelic-php5 state=present
  notify:
    - restart nginx
    - restart php-fpm
    - restart newrelic-sysmond
- name: check newrelic-install executed
  command: ls /etc/init.d/newrelic-daemon
  register: result
  ignore_errors: True
- name: exec newrelic-install
  shell: sh -c 'echo {{ newrelic_license }} | newrelic-install install'
  when: result|failed
- name: php.ini newrelic enable
  lineinfile: dest=/etc/php.ini
              regexp=''
              insertafter=EOF
              line='newrelic.license="{{ newrelic_license }}"'
  notify:
    - restart nginx
    - restart php-fpm
